# Generated by Django 4.0.3 on 2022-04-22 07:24

import datetime
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSubscribe',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('subscription_date', models.DateField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': 'NewsFeeds',
            },
        ),
    ]
