# Generated by Django 4.0.3 on 2022-04-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bit_talk_misc_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailsubscribe',
            options={'verbose_name_plural': 'EmailSubscribers'},
        ),
        migrations.AlterField(
            model_name='emailsubscribe',
            name='subscription_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
