# Generated by Django 3.2.13 on 2022-06-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bit_talk_app_main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsFeed',
        ),
        migrations.AlterField(
            model_name='user',
            name='preffered_lang',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
